name: Build and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

      - name: Build Docker image
        run: docker build -t broken_link_finder .

      - name: Run Docker container with volume mount
        run: docker run -v "${{ github.workspace }}/output:/app/output" broken_link_finder

      # Flatten the output structure by copying files to a temporary folder
      - name: Flatten output structure
        run: |
          mkdir -p flat
          cp output/* flat/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: broken-report
          path: flat/

      # Clean up: remove the temporary flat folder and empty the output directory
      - name: Clean up temporary directories
        run: |
          rm -rf flat
          rm -rf output/*
